#apiVersion: v1
#
#kind: Pod
#
#metadata:
#  name: nginx
#
#  labels:
#    app: nginx
#    tier: frontend
#
#spec:
#  containers:
#    - name: nginx
#      image: nginx


#apiVersion: v1
#kind: Pod
#metadata:
#  name: ubuntu-sleeper-2
#spec:
#  containers:
#    - name: ubuntu
#      image: ubuntu
#      command:
#        - sleep
#        - "5000"

apiVersion: v1
kind: Pod
metadata:
  name: webapp-green
  labels:
    name: webapp-green
spec:
  containers:
    - name: simple-webapp
      image: kodekloud/webapp-color
      args: [ "--color", "green" ]
