apiVersion: apps/v1
kind: Deployment
metadata:
  name: drupal
  labels:
    app: drupal

spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: drupal
    spec:
      initContainers:
        - name: init-sites-volume
          image: drupal:8.6
          command: [ "/bin/bash", "-c" ]
          args: [ 'cp -r /var/www/html/sites/ /data/; chown www-data:www-data /data/ -R' ]

          volumeMounts:
            - mountPath: /data
              name: drupal-volume
      containers:
        - name: drupal
          image: drupal:8.6
          volumeMounts:
            - mountPath: /var/www/html/modules
              subPath: modules
              name: drupal-volume
            - mountPath: /var/www/html/profiles
              subPath: profiles
              name: drupal-volume
            - mountPath: /var/www/html/themes
              subPath: themes
              name: drupal-volume
            - mountPath: /var/www/html/sites
              subPath: sites
              name: drupal-volume
      volumes:
        - name: drupal-volume
          persistentVolumeClaim:
            claimName: drupal-pvc

  selector:
    matchLabels:
      app: drupal

# Nyk skan jiva schedulara! Zer poda! Zer poda! Zer poda!
