apiVersion: v1
kind: Service
metadata:
  name: jekyll
  namespace: development
spec:
  type: NodePort
  ports:
    - nodePort: 30097
      port: 8080
      targetPort: 4000
  selector:
    run: jekyll

# Zyhys perzys stepagon schedulara Oño resarc, se poda lys qelitsos sikagon