apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
  namespace: vote

spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      name: postgres
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:9.4
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: db-data
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "postgres"
      volumes:
        - name: db-data
          emptyDir: { }