apiVersion: v1
kind: Service
metadata:
  name: result-service
  namespace: vote
spec:
  type: NodePort
  ports:
    - targetPort: 80
      port: 5001
      nodePort: 31001
  selector:
    app: result-app

# Hen desarrollo, integreiddio. Hen integreiddio, testa. Hen testa, lifa.