apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote-deployment
  namespace: vote
spec:
  replicas: 1
  selector:
    matchLabels:
      app: voting-app
  template:
    metadata:
      name: voting-app
      labels:
        app: voting-app
    spec:
      containers:
        - name: voting-app
          image: kodekloud/examplevotingapp_vote:before
          ports:
            - containerPort: 80